import { ScheduledGame, DetailedGameFeed, PlayerProfile, DivisionStanding } from "../types";

// Famous real player IDs for authentic headshots & logos
// Shohei Ohtani: 660271
// Aaron Judge: 592450
// Mookie Betts: 605141
// Juan Soto: 665742
// Paul Skenes: 694973
// Gerrit Cole: 543037
// Ronald Acuña Jr.: 660670
// Freddie Freeman: 518692
// Tarik Skubal: 669373
// Yoshinobu Yamamoto: 808967

export const MOCK_SCHEDULE_GAMES: ScheduledGame[] = [
  {
    gamePk: 747001,
    gameDate: new Date().toISOString(),
    officialDate: new Date().toISOString().split("T")[0],
    status: {
      abstractGameState: "Live",
      codedGameState: "I",
      detailedState: "In Progress",
      statusCode: "I",
    },
    teams: {
      away: {
        team: {
          id: 147,
          name: "New York Yankees",
          teamName: "Yankees",
          abbreviation: "NYY",
          shortName: "Yankees",
          logoUrl: "https://www.mlbstatic.com/team-logos/147.svg",
          record: { wins: 94, losses: 68, pct: ".580" },
        },
        score: 5,
        leagueRecord: { wins: 94, losses: 68, pct: ".580" },
        probablePitcher: {
          id: 543037,
          fullName: "Gerrit Cole",
          headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/543037/headshot/silo/current",
          era: "3.41",
          wins: 8,
          losses: 5,
        },
      },
      home: {
        team: {
          id: 119,
          name: "Los Angeles Dodgers",
          teamName: "Dodgers",
          abbreviation: "LAD",
          shortName: "Dodgers",
          logoUrl: "https://www.mlbstatic.com/team-logos/119.svg",
          record: { wins: 98, losses: 64, pct: ".605" },
        },
        score: 6,
        leagueRecord: { wins: 98, losses: 64, pct: ".605" },
        probablePitcher: {
          id: 808967,
          fullName: "Yoshinobu Yamamoto",
          headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/808967/headshot/silo/current",
          era: "3.00",
          wins: 7,
          losses: 2,
        },
      },
    },
    linescore: {
      currentInning: 7,
      currentInningOrdinal: "7th",
      inningState: "Bottom",
      isTopInning: false,
      innings: [
        { num: 1, away: { runs: 0, hits: 1, errors: 0 }, home: { runs: 2, hits: 2, errors: 0 } },
        { num: 2, away: { runs: 1, hits: 2, errors: 0 }, home: { runs: 0, hits: 0, errors: 0 } },
        { num: 3, away: { runs: 2, hits: 3, errors: 0 }, home: { runs: 1, hits: 1, errors: 0 } },
        { num: 4, away: { runs: 0, hits: 0, errors: 0 }, home: { runs: 0, hits: 1, errors: 0 } },
        { num: 5, away: { runs: 1, hits: 1, errors: 0 }, home: { runs: 2, hits: 3, errors: 0 } },
        { num: 6, away: { runs: 1, hits: 1, errors: 0 }, home: { runs: 0, hits: 1, errors: 0 } },
        { num: 7, away: { runs: 0, hits: 0, errors: 0 }, home: { runs: 1, hits: 2, errors: 0 } },
      ],
      teams: {
        away: { runs: 5, hits: 8, errors: 0 },
        home: { runs: 6, hits: 10, errors: 1 },
      },
      balls: 2,
      strikes: 1,
      outs: 1,
    },
    venue: { name: "Dodger Stadium" },
    broadcasts: ["FOX", "ESPN Radio"],
    weather: { condition: "Clear", temp: "74°F", wind: "8 mph Out To CF" },
  },
  {
    gamePk: 747002,
    gameDate: new Date().toISOString(),
    officialDate: new Date().toISOString().split("T")[0],
    status: {
      abstractGameState: "Live",
      codedGameState: "I",
      detailedState: "In Progress",
      statusCode: "I",
    },
    teams: {
      away: {
        team: {
          id: 144,
          name: "Atlanta Braves",
          teamName: "Braves",
          abbreviation: "ATL",
          shortName: "Braves",
          logoUrl: "https://www.mlbstatic.com/team-logos/144.svg",
          record: { wins: 89, losses: 73, pct: ".549" },
        },
        score: 3,
        leagueRecord: { wins: 89, losses: 73, pct: ".549" },
        probablePitcher: {
          id: 660670,
          fullName: "Spencer Strider",
          headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/675911/headshot/silo/current",
          era: "3.86",
          wins: 11,
          losses: 6,
        },
      },
      home: {
        team: {
          id: 143,
          name: "Philadelphia Phillies",
          teamName: "Phillies",
          abbreviation: "PHI",
          shortName: "Phillies",
          logoUrl: "https://www.mlbstatic.com/team-logos/143.svg",
          record: { wins: 95, losses: 67, pct: ".586" },
        },
        score: 4,
        leagueRecord: { wins: 95, losses: 67, pct: ".586" },
        probablePitcher: {
          id: 605483,
          fullName: "Zack Wheeler",
          headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/554430/headshot/silo/current",
          era: "2.57",
          wins: 16,
          losses: 7,
        },
      },
    },
    linescore: {
      currentInning: 5,
      currentInningOrdinal: "5th",
      inningState: "Top",
      isTopInning: true,
      innings: [
        { num: 1, away: { runs: 1, hits: 2, errors: 0 }, home: { runs: 0, hits: 1, errors: 0 } },
        { num: 2, away: { runs: 0, hits: 0, errors: 0 }, home: { runs: 2, hits: 3, errors: 0 } },
        { num: 3, away: { runs: 2, hits: 2, errors: 0 }, home: { runs: 0, hits: 0, errors: 0 } },
        { num: 4, away: { runs: 0, hits: 1, errors: 0 }, home: { runs: 2, hits: 2, errors: 0 } },
      ],
      teams: {
        away: { runs: 3, hits: 5, errors: 0 },
        home: { runs: 4, hits: 6, errors: 0 },
      },
      balls: 1,
      strikes: 2,
      outs: 2,
    },
    venue: { name: "Citizens Bank Park" },
    broadcasts: ["TBS"],
  },
  {
    gamePk: 747003,
    gameDate: new Date().toISOString(),
    officialDate: new Date().toISOString().split("T")[0],
    status: {
      abstractGameState: "Final",
      codedGameState: "F",
      detailedState: "Final",
      statusCode: "F",
    },
    teams: {
      away: {
        team: {
          id: 135,
          name: "San Diego Padres",
          teamName: "Padres",
          abbreviation: "SD",
          shortName: "Padres",
          logoUrl: "https://www.mlbstatic.com/team-logos/135.svg",
        },
        score: 7,
        isWinner: true,
      },
      home: {
        team: {
          id: 115,
          name: "Colorado Rockies",
          teamName: "Rockies",
          abbreviation: "COL",
          shortName: "Rockies",
          logoUrl: "https://www.mlbstatic.com/team-logos/115.svg",
        },
        score: 2,
        isWinner: false,
      },
    },
    linescore: {
      currentInning: 9,
      currentInningOrdinal: "9th",
      inningState: "End",
      innings: [],
      teams: {
        away: { runs: 7, hits: 12, errors: 0 },
        home: { runs: 2, hits: 6, errors: 2 },
      },
    },
    decisions: {
      winner: { id: 669373, fullName: "Michael King", wins: 13, losses: 9, era: "2.95" },
      loser: { id: 605151, fullName: "Kyle Freeland", wins: 5, losses: 14, era: "5.01" },
    },
    venue: { name: "Coors Field" },
  },
  {
    gamePk: 747004,
    gameDate: new Date().toISOString(),
    officialDate: new Date().toISOString().split("T")[0],
    status: {
      abstractGameState: "Live",
      codedGameState: "I",
      detailedState: "In Progress",
      statusCode: "I",
    },
    teams: {
      away: {
        team: {
          id: 111,
          name: "Boston Red Sox",
          teamName: "Red Sox",
          abbreviation: "BOS",
          shortName: "Red Sox",
          logoUrl: "https://www.mlbstatic.com/team-logos/111.svg",
        },
        score: 4,
      },
      home: {
        team: {
          id: 110,
          name: "Baltimore Orioles",
          teamName: "Orioles",
          abbreviation: "BAL",
          shortName: "Orioles",
          logoUrl: "https://www.mlbstatic.com/team-logos/110.svg",
        },
        score: 3,
      },
    },
    linescore: {
      currentInning: 4,
      currentInningOrdinal: "4th",
      inningState: "Top",
      innings: [],
      teams: {
        away: { runs: 4, hits: 6, errors: 0 },
        home: { runs: 3, hits: 5, errors: 1 },
      },
    },
    venue: { name: "Camden Yards" },
    broadcasts: ["NESN", "MASN"],
  },
  {
    gamePk: 747005,
    gameDate: new Date().toISOString(),
    officialDate: new Date().toISOString().split("T")[0],
    status: {
      abstractGameState: "Preview",
      codedGameState: "S",
      detailedState: "Scheduled",
      statusCode: "S",
    },
    teams: {
      away: {
        team: {
          id: 112,
          name: "Chicago Cubs",
          teamName: "Cubs",
          abbreviation: "CHC",
          shortName: "Cubs",
          logoUrl: "https://www.mlbstatic.com/team-logos/112.svg",
        },
        score: 0,
      },
      home: {
        team: {
          id: 138,
          name: "St. Louis Cardinals",
          teamName: "Cardinals",
          abbreviation: "STL",
          shortName: "Cardinals",
          logoUrl: "https://www.mlbstatic.com/team-logos/138.svg",
        },
        score: 0,
      },
    },
    venue: { name: "Busch Stadium" },
    broadcasts: ["MLB Network", "BSMW"],
  },
  {
    gamePk: 747006,
    gameDate: new Date().toISOString(),
    officialDate: new Date().toISOString().split("T")[0],
    status: {
      abstractGameState: "Preview",
      codedGameState: "S",
      detailedState: "Scheduled",
      statusCode: "S",
    },
    teams: {
      away: {
        team: {
          id: 117,
          name: "Houston Astros",
          teamName: "Astros",
          abbreviation: "HOU",
          shortName: "Astros",
          logoUrl: "https://www.mlbstatic.com/team-logos/117.svg",
        },
        score: 0,
      },
      home: {
        team: {
          id: 140,
          name: "Texas Rangers",
          teamName: "Rangers",
          abbreviation: "TEX",
          shortName: "Rangers",
          logoUrl: "https://www.mlbstatic.com/team-logos/140.svg",
        },
        score: 0,
      },
    },
    venue: { name: "Globe Life Field" },
    broadcasts: ["BSSW"],
  },
  {
    gamePk: 747007,
    gameDate: new Date().toISOString(),
    officialDate: new Date().toISOString().split("T")[0],
    status: {
      abstractGameState: "Preview",
      codedGameState: "S",
      detailedState: "Scheduled",
      statusCode: "S",
    },
    teams: {
      away: {
        team: {
          id: 137,
          name: "San Francisco Giants",
          teamName: "Giants",
          abbreviation: "SF",
          shortName: "Giants",
          logoUrl: "https://www.mlbstatic.com/team-logos/137.svg",
        },
        score: 0,
      },
      home: {
        team: {
          id: 109,
          name: "Arizona Diamondbacks",
          teamName: "D-backs",
          abbreviation: "ARI",
          shortName: "D-backs",
          logoUrl: "https://www.mlbstatic.com/team-logos/109.svg",
        },
        score: 0,
      },
    },
    venue: { name: "Chase Field" },
    broadcasts: ["NBCSBA"],
  },
  {
    gamePk: 747008,
    gameDate: new Date().toISOString(),
    officialDate: new Date().toISOString().split("T")[0],
    status: {
      abstractGameState: "Final",
      codedGameState: "F",
      detailedState: "Final",
      statusCode: "F",
    },
    teams: {
      away: {
        team: {
          id: 121,
          name: "New York Mets",
          teamName: "Mets",
          abbreviation: "NYM",
          shortName: "Mets",
          logoUrl: "https://www.mlbstatic.com/team-logos/121.svg",
        },
        score: 6,
        isWinner: true,
      },
      home: {
        team: {
          id: 120,
          name: "Washington Nationals",
          teamName: "Nationals",
          abbreviation: "WSH",
          shortName: "Nationals",
          logoUrl: "https://www.mlbstatic.com/team-logos/120.svg",
        },
        score: 1,
        isWinner: false,
      },
    },
    linescore: {
      currentInning: 9,
      currentInningOrdinal: "9th",
      inningState: "End",
      innings: [],
      teams: {
        away: { runs: 6, hits: 10, errors: 0 },
        home: { runs: 1, hits: 4, errors: 1 },
      },
    },
    venue: { name: "Nationals Park" },
  },
];

export const MOCK_DETAILED_GAME: DetailedGameFeed = {
  gamePk: 747001,
  gameData: {
    game: { pk: 747001, type: "R", season: "2024" },
    datetime: { dateTime: new Date().toISOString(), originalDate: new Date().toISOString().split("T")[0], time: "7:10", ampm: "PM" },
    status: { abstractGameState: "Live", codedGameState: "I", detailedState: "In Progress", statusCode: "I" },
    teams: {
      away: {
        team: { id: 147, name: "New York Yankees", teamName: "Yankees", abbreviation: "NYY", shortName: "Yankees", logoUrl: "https://www.mlbstatic.com/team-logos/147.svg" },
      },
      home: {
        team: { id: 119, name: "Los Angeles Dodgers", teamName: "Dodgers", abbreviation: "LAD", shortName: "Dodgers", logoUrl: "https://www.mlbstatic.com/team-logos/119.svg" },
      },
    },
    venue: { name: "Dodger Stadium", location: { city: "Los Angeles", state: "CA" } },
    weather: { condition: "Clear Skies", temp: "74°F", wind: "8 mph Out To CF" },
  },
  liveData: {
    linescore: {
      currentInning: 7,
      currentInningOrdinal: "7th",
      inningState: "Bottom",
      isTopInning: false,
      innings: [
        { num: 1, away: { runs: 0, hits: 1, errors: 0 }, home: { runs: 2, hits: 2, errors: 0 } },
        { num: 2, away: { runs: 1, hits: 2, errors: 0 }, home: { runs: 0, hits: 0, errors: 0 } },
        { num: 3, away: { runs: 2, hits: 3, errors: 0 }, home: { runs: 1, hits: 1, errors: 0 } },
        { num: 4, away: { runs: 0, hits: 0, errors: 0 }, home: { runs: 0, hits: 1, errors: 0 } },
        { num: 5, away: { runs: 1, hits: 1, errors: 0 }, home: { runs: 2, hits: 3, errors: 0 } },
        { num: 6, away: { runs: 1, hits: 1, errors: 0 }, home: { runs: 0, hits: 1, errors: 0 } },
        { num: 7, away: { runs: 0, hits: 0, errors: 0 }, home: { runs: 1, hits: 2, errors: 0 } },
      ],
      teams: {
        away: { runs: 5, hits: 8, errors: 0, leftOnBase: 6 },
        home: { runs: 6, hits: 10, errors: 1, leftOnBase: 7 },
      },
      balls: 2,
      strikes: 1,
      outs: 1,
    },
    matchup: {
      batter: {
        id: 660271,
        fullName: "Shohei Ohtani",
        headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/660271/headshot/silo/current",
        jerseyNumber: "17",
        primaryPosition: { code: "D", name: "Designated Hitter", type: "Hitter", abbreviation: "DH" },
        batSide: { code: "L", description: "Left" },
        seasonStats: { avg: ".310", hr: 54, rbi: 130, ops: "1.036" },
      },
      pitcher: {
        id: 543037,
        fullName: "Gerrit Cole",
        headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/543037/headshot/silo/current",
        jerseyNumber: "45",
        primaryPosition: { code: "1", name: "Pitcher", type: "Pitcher", abbreviation: "P" },
        pitchHand: { code: "R", description: "Right" },
        seasonStats: { era: "3.41", wins: 8, losses: 5, so: 99, ip: "95.0" },
        pitchCount: 94,
      },
      postOnFirst: {
        id: 605141,
        fullName: "Mookie Betts",
        headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/605141/headshot/silo/current",
      },
      postOnSecond: {
        id: 518692,
        fullName: "Freddie Freeman",
        headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/518692/headshot/silo/current",
      },
    },
    plays: [
      {
        id: "play-701",
        index: 12,
        inning: 7,
        halfInning: "bottom",
        event: "Home Run",
        eventType: "home_run",
        description: "Shohei Ohtani homers (55) on a fly ball to right-center field (438 ft). Mookie Betts scores. Freddie Freeman scores.",
        isScoringPlay: true,
        isOut: false,
        hasOut: false,
        runsScored: 3,
        awayScore: 5,
        homeScore: 6,
        batter: { id: 660271, fullName: "Shohei Ohtani" },
        pitcher: { id: 543037, fullName: "Gerrit Cole" },
        statcast: {
          pitchType: "FF",
          pitchTypeDescription: "4-Seam Fastball",
          pitchSpeedMph: 98.4,
          spinRateRpm: 2480,
          exitVelocityMph: 114.2,
          launchAngleDeg: 28,
          hitDistanceFt: 438,
          trajectory: "fly_ball",
          zoneLocation: { x: 0.1, y: 0.4 },
          isStrike: true,
        },
        timestamp: "7:45 PM",
      },
      {
        id: "play-702",
        index: 11,
        inning: 7,
        halfInning: "bottom",
        event: "Single",
        eventType: "single",
        description: "Mookie Betts singles on a line drive to left field.",
        isScoringPlay: false,
        isOut: false,
        hasOut: false,
        awayScore: 5,
        homeScore: 3,
        batter: { id: 605141, fullName: "Mookie Betts" },
        pitcher: { id: 543037, fullName: "Gerrit Cole" },
        statcast: {
          pitchType: "SL",
          pitchTypeDescription: "Slider",
          pitchSpeedMph: 88.6,
          spinRateRpm: 2620,
          exitVelocityMph: 104.5,
          launchAngleDeg: 14,
          hitDistanceFt: 245,
          trajectory: "line_drive",
          zoneLocation: { x: -0.4, y: -0.2 },
          isStrike: true,
        },
        timestamp: "7:41 PM",
      },
      {
        id: "play-703",
        index: 10,
        inning: 7,
        halfInning: "top",
        event: "Strikeout",
        eventType: "strikeout",
        description: "Aaron Judge strikes out swinging on a 99 mph fastball.",
        isScoringPlay: false,
        isOut: true,
        hasOut: true,
        awayScore: 5,
        homeScore: 3,
        batter: { id: 592450, fullName: "Aaron Judge" },
        pitcher: { id: 808967, fullName: "Yoshinobu Yamamoto" },
        statcast: {
          pitchType: "FF",
          pitchTypeDescription: "4-Seam Fastball",
          pitchSpeedMph: 99.1,
          spinRateRpm: 2510,
          isStrike: true,
          isWhiff: true,
          zoneLocation: { x: 0.8, y: 0.9 },
        },
        timestamp: "7:30 PM",
      },
    ],
    scoringPlays: [],
    boxscore: {
      teams: {
        away: {
          team: { id: 147, name: "New York Yankees", teamName: "Yankees", abbreviation: "NYY" },
          battingOrder: [
            {
              person: { id: 665742, fullName: "Juan Soto", headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/665742/headshot/silo/current" },
              jerseyNumber: "22",
              position: { abbreviation: "RF", name: "Right Fielder" },
              stats: { batting: { atBats: 3, runs: 2, hits: 2, rbi: 1, homeRuns: 1, strikeOuts: 0, baseOnBalls: 1, avg: ".288", ops: ".989" } },
            },
            {
              person: { id: 592450, fullName: "Aaron Judge", headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/592450/headshot/silo/current" },
              jerseyNumber: "99",
              position: { abbreviation: "CF", name: "Center Fielder" },
              stats: { batting: { atBats: 4, runs: 1, hits: 2, rbi: 3, homeRuns: 1, strikeOuts: 1, baseOnBalls: 0, avg: ".322", ops: "1.159" } },
            },
          ],
          pitchers: [
            {
              person: { id: 543037, fullName: "Gerrit Cole", headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/543037/headshot/silo/current" },
              jerseyNumber: "45",
              position: { abbreviation: "P", name: "Pitcher" },
              stats: { pitching: { inningsPitched: "6.1", hits: 8, runs: 5, earnedRuns: 5, baseOnBalls: 2, strikeOuts: 7, homeRuns: 2, era: "3.41", numberOfPitches: 94 } },
            },
          ],
          bench: [],
          teamStats: { batting: { runs: 5, hits: 8, errors: 0, rbi: 5, hr: 2, bb: 3, so: 8 } },
        },
        home: {
          team: { id: 119, name: "Los Angeles Dodgers", teamName: "Dodgers", abbreviation: "LAD" },
          battingOrder: [
            {
              person: { id: 660271, fullName: "Shohei Ohtani", headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/660271/headshot/silo/current" },
              jerseyNumber: "17",
              position: { abbreviation: "DH", name: "Designated Hitter" },
              stats: { batting: { atBats: 4, runs: 2, hits: 3, rbi: 4, homeRuns: 2, strikeOuts: 1, baseOnBalls: 0, avg: ".310", ops: "1.036" } },
            },
            {
              person: { id: 605141, fullName: "Mookie Betts", headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/605141/headshot/silo/current" },
              jerseyNumber: "50",
              position: { abbreviation: "SS", name: "Shortstop" },
              stats: { batting: { atBats: 3, runs: 2, hits: 2, rbi: 1, homeRuns: 0, strikeOuts: 0, baseOnBalls: 1, avg: ".289", ops: ".863" } },
            },
            {
              person: { id: 518692, fullName: "Freddie Freeman", headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/518692/headshot/silo/current" },
              jerseyNumber: "5",
              position: { abbreviation: "1B", name: "First Baseman" },
              stats: { batting: { atBats: 4, runs: 1, hits: 2, rbi: 1, homeRuns: 1, strikeOuts: 0, baseOnBalls: 0, avg: ".282", ops: ".854" } },
            },
          ],
          pitchers: [
            {
              person: { id: 808967, fullName: "Yoshinobu Yamamoto", headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_213,q_auto:best/v1/people/808967/headshot/silo/current" },
              jerseyNumber: "18",
              position: { abbreviation: "P", name: "Pitcher" },
              stats: { pitching: { inningsPitched: "6.0", hits: 7, runs: 5, earnedRuns: 4, baseOnBalls: 1, strikeOuts: 8, homeRuns: 2, era: "3.00", numberOfPitches: 89 } },
            },
          ],
          bench: [],
          teamStats: { batting: { runs: 6, hits: 10, errors: 1, rbi: 6, hr: 3, bb: 2, so: 6 } },
        },
      },
    },
  },
};

export const MOCK_PLAYER_PROFILES: Record<number, PlayerProfile> = {
  660271: {
    id: 660271,
    fullName: "Shohei Ohtani",
    firstName: "Shohei",
    lastName: "Ohtani",
    primaryNumber: "17",
    birthDate: "1994-07-05",
    currentAge: 30,
    birthCity: "Oshu",
    birthCountry: "Japan",
    height: "6' 4\"",
    weight: 210,
    active: true,
    currentTeam: {
      id: 119,
      name: "Los Angeles Dodgers",
      teamName: "Dodgers",
      abbreviation: "LAD",
      shortName: "Dodgers",
      logoUrl: "https://www.mlbstatic.com/team-logos/119.svg",
    },
    primaryPosition: { code: "D", name: "Designated Hitter", type: "Hitter", abbreviation: "DH" },
    batSide: { code: "L", description: "Left" },
    pitchHand: { code: "R", description: "Right" },
    headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_400,q_auto:best/v1/people/660271/headshot/silo/current",
    draftYear: 2017,
    draftDetails: {
      year: 2017,
      round: "International FA",
      pickOverall: 1,
      pickInRound: 1,
      team: { name: "Los Angeles Angels", abbreviation: "LAA" },
      school: "Hanamaki Higashi High School (Japan)",
    },
    mlbDebutDate: "2018-03-29",
    awards: [
      { id: "MVP_AL_2021", name: "AL Most Valuable Player", season: "2021", notes: "Unanimous Winner" },
      { id: "MVP_AL_2023", name: "AL Most Valuable Player", season: "2023", notes: "Unanimous Winner" },
      { id: "MVP_NL_2024", name: "NL Most Valuable Player", season: "2024", notes: "First 50/50 Season in MLB History" },
      { id: "ROY_AL_2018", name: "AL Rookie of the Year", season: "2018" },
      { id: "SILVER_2021", name: "Silver Slugger Award", season: "2021" },
      { id: "ALL_STAR", name: "4x MLB All-Star Selection", season: "2021-2024" },
    ],
    careerMilestones: [
      "Inaugural 50/50 Club Member (54 HR, 59 SB in 2024)",
      "First player in MLB history with 10+ Pitching Wins and 30+ HR in same season",
      "World Series Champion (2024)",
      "2x Unanimous MVP & 3x MVP Overall",
    ],
    stats: {
      currentSeasonBatting: {
        avg: ".310",
        hr: 54,
        rbi: 130,
        ops: "1.036",
        obp: ".390",
        slg: ".646",
        hits: 197,
        doubles: 38,
        triples: 7,
        runs: 134,
        sb: 59,
        bb: 81,
        so: 162,
        war: 9.2,
      },
      careerBatting: {
        avg: ".282",
        hr: 225,
        rbi: 567,
        ops: ".945",
        hits: 878,
        gamesPlayed: 860,
      },
      careerPitching: {
        era: "3.01",
        whip: "1.08",
        wins: 38,
        losses: 19,
        so: 608,
        ip: "481.2",
      },
      currentSeasonFielding: {
        fieldingPct: "1.000",
        position: "DH",
        errors: 0,
        assists: 0,
        putOuts: 0,
      },
    },
    statcastHighlights: {
      avgExitVelocityMph: 95.8,
      maxExitVelocityMph: 119.2,
      hardHitPct: 54.3,
      barrelPct: 19.8,
      fastballVeloMph: 98.6,
      spinRateRpm: 2420,
    },
  },
  592450: {
    id: 592450,
    fullName: "Aaron Judge",
    firstName: "Aaron",
    lastName: "Judge",
    primaryNumber: "99",
    birthDate: "1992-04-26",
    currentAge: 32,
    birthCity: "Linden",
    birthCountry: "USA",
    height: "6' 7\"",
    weight: 282,
    active: true,
    currentTeam: {
      id: 147,
      name: "New York Yankees",
      teamName: "Yankees",
      abbreviation: "NYY",
      shortName: "Yankees",
      logoUrl: "https://www.mlbstatic.com/team-logos/147.svg",
    },
    primaryPosition: { code: "9", name: "Outfielder", type: "Hitter", abbreviation: "CF" },
    batSide: { code: "R", description: "Right" },
    pitchHand: { code: "R", description: "Right" },
    headshotUrl: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:silo:current.png/w_400,q_auto:best/v1/people/592450/headshot/silo/current",
    draftYear: 2013,
    draftDetails: {
      year: 2013,
      round: "1",
      pickOverall: 32,
      pickInRound: 32,
      team: { name: "New York Yankees", abbreviation: "NYY" },
      school: "California State University, Fresno",
    },
    mlbDebutDate: "2016-08-13",
    awards: [
      { id: "MVP_AL_2022", name: "AL Most Valuable Player", season: "2022", notes: "Single-season AL HR Record (62)" },
      { id: "MVP_AL_2024", name: "AL Most Valuable Player", season: "2024", notes: "58 HR, 144 RBI" },
      { id: "ROY_AL_2017", name: "AL Rookie of the Year", season: "2017" },
      { id: "ALL_STAR", name: "6x MLB All-Star", season: "2017-2024" },
    ],
    careerMilestones: [
      "American League Single-Season HR Record Holder (62 HR in 2022)",
      "Fastest player to 300 Career Home Runs in MLB History (955 games)",
      "Yankees Team Captain (Named 16th Captain in franchise history)",
    ],
    stats: {
      currentSeasonBatting: {
        avg: ".322",
        hr: 58,
        rbi: 144,
        ops: "1.159",
        obp: ".458",
        slg: ".701",
        hits: 180,
        doubles: 36,
        triples: 1,
        runs: 122,
        sb: 10,
        bb: 133,
        so: 171,
        war: 10.8,
      },
      careerBatting: {
        avg: ".288",
        hr: 315,
        rbi: 715,
        ops: "1.010",
        hits: 1020,
        gamesPlayed: 993,
      },
      currentSeasonFielding: {
        fieldingPct: ".992",
        position: "CF",
        errors: 2,
        assists: 7,
        putOuts: 240,
      },
    },
    statcastHighlights: {
      avgExitVelocityMph: 96.2,
      maxExitVelocityMph: 121.1,
      hardHitPct: 60.8,
      barrelPct: 25.6,
    },
  },
};

export const MOCK_STANDINGS: DivisionStanding[] = [
  {
    division: { id: 201, name: "American League East", nameShort: "AL East" },
    league: { id: 103, name: "American League" },
    teamRecords: [
      {
        team: { id: 147, name: "New York Yankees", teamName: "Yankees", abbreviation: "NYY", shortName: "Yankees", logoUrl: "https://www.mlbstatic.com/team-logos/147.svg" },
        divisionRank: "1",
        leagueRank: "1",
        sportRank: "2",
        gamesPlayed: 162,
        wins: 94,
        losses: 68,
        pct: ".580",
        gamesBehind: "-",
        wildCardGamesBehind: "-",
        streak: { streakCode: "W2" },
        runsScored: 815,
        runsAllowed: 668,
        runDifferential: 147,
        homeRecord: "44-37",
        awayRecord: "50-31",
        lastTen: "6-4",
        clinchIndicator: "y",
      },
      {
        team: { id: 110, name: "Baltimore Orioles", teamName: "Orioles", abbreviation: "BAL", shortName: "Orioles", logoUrl: "https://www.mlbstatic.com/team-logos/110.svg" },
        divisionRank: "2",
        leagueRank: "4",
        sportRank: "5",
        gamesPlayed: 162,
        wins: 91,
        losses: 71,
        pct: ".562",
        gamesBehind: "3.0",
        wildCardGamesBehind: "+2.0",
        streak: { streakCode: "W3" },
        runsScored: 786,
        runsAllowed: 699,
        runDifferential: 87,
        homeRecord: "44-37",
        awayRecord: "47-34",
        lastTen: "7-3",
        clinchIndicator: "wc",
      },
      {
        team: { id: 111, name: "Boston Red Sox", teamName: "Red Sox", abbreviation: "BOS", shortName: "Red Sox", logoUrl: "https://www.mlbstatic.com/team-logos/111.svg" },
        divisionRank: "3",
        leagueRank: "8",
        sportRank: "14",
        gamesPlayed: 162,
        wins: 81,
        losses: 81,
        pct: ".500",
        gamesBehind: "13.0",
        wildCardGamesBehind: "5.0",
        streak: { streakCode: "L1" },
        runsScored: 752,
        runsAllowed: 742,
        runDifferential: 10,
        homeRecord: "38-43",
        awayRecord: "43-38",
        lastTen: "4-6",
      },
    ],
  },
  {
    division: { id: 203, name: "National League West", nameShort: "NL West" },
    league: { id: 104, name: "National League" },
    teamRecords: [
      {
        team: { id: 119, name: "Los Angeles Dodgers", teamName: "Dodgers", abbreviation: "LAD", shortName: "Dodgers", logoUrl: "https://www.mlbstatic.com/team-logos/119.svg" },
        divisionRank: "1",
        leagueRank: "1",
        sportRank: "1",
        gamesPlayed: 162,
        wins: 98,
        losses: 64,
        pct: ".605",
        gamesBehind: "-",
        wildCardGamesBehind: "-",
        streak: { streakCode: "W5" },
        runsScored: 842,
        runsAllowed: 686,
        runDifferential: 156,
        homeRecord: "52-29",
        awayRecord: "46-35",
        lastTen: "8-2",
        clinchIndicator: "z",
      },
      {
        team: { id: 135, name: "San Diego Padres", teamName: "Padres", abbreviation: "SD", shortName: "Padres", logoUrl: "https://www.mlbstatic.com/team-logos/135.svg" },
        divisionRank: "2",
        leagueRank: "4",
        sportRank: "4",
        gamesPlayed: 162,
        wins: 93,
        losses: 69,
        pct: ".574",
        gamesBehind: "5.0",
        wildCardGamesBehind: "+4.0",
        streak: { streakCode: "W1" },
        runsScored: 760,
        runsAllowed: 669,
        runDifferential: 91,
        homeRecord: "45-36",
        awayRecord: "48-33",
        lastTen: "7-3",
        clinchIndicator: "wc",
      },
    ],
  },
];
